//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPNClient.Properties;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
{
    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

    public static Settings Default
    {
        get
        {
            return defaultInstance;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string SavedUsername
    {
        get
        {
            return ((string)(this["SavedUsername"]));
        }
        set
        {
            this["SavedUsername"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool RememberMe
    {
        get
        {
            return ((bool)(this["RememberMe"]));
        }
        set
        {
            this["RememberMe"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool StartWithWindows
    {
        get
        {
            return ((bool)(this["StartWithWindows"]));
        }
        set
        {
            this["StartWithWindows"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool AutoConnect
    {
        get
        {
            return ((bool)(this["AutoConnect"]));
        }
        set
        {
            this["AutoConnect"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    public bool MinimizeToTray
    {
        get
        {
            return ((bool)(this["MinimizeToTray"]));
        }
        set
        {
            this["MinimizeToTray"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool KillSwitch
    {
        get
        {
            return ((bool)(this["KillSwitch"]));
        }
        set
        {
            this["KillSwitch"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("1400")]
    public int MtuSize
    {
        get
        {
            return ((int)(this["MtuSize"]));
        }
        set
        {
            this["MtuSize"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string CustomDns
    {
        get
        {
            return ((string)(this["CustomDns"]));
        }
        set
        {
            this["CustomDns"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    public bool EnableLogging
    {
        get
        {
            return ((bool)(this["EnableLogging"]));
        }
        set
        {
            this["EnableLogging"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("30")]
    public int ConnectionTimeout
    {
        get
        {
            return ((int)(this["ConnectionTimeout"]));
        }
        set
        {
            this["ConnectionTimeout"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("vpn.example.com")]
    public string LastServerAddress
    {
        get
        {
            return ((string)(this["LastServerAddress"]));
        }
        set
        {
            this["LastServerAddress"] = value;
        }
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("443")]
    public int LastServerPort
    {
        get
        {
            return ((int)(this["LastServerPort"]));
        }
        set
        {
            this["LastServerPort"] = value;
        }
    }
}
